Enhance and add the integration.
osk2/line-bot pull request #1
Opened 2021-04-23 15:07 UTC by niceboygithub

1. Can use Integration to add another LINE-bot
2. Flexible message format.
3. Update README.md

2021-04-28 02:35 UTC, osk2 commented
Hi, @niceboygithub 
Is this PR finish yet? It seems you still pushing more commits

2021-04-28 11:18 UTC, tsunglung commented
No bug found now. 
The new improvement will be the next stage.

2021-05-05 04:52 UTC, osk2 commented
Just tested this PR, I followed steps in readme but no notify service had been added into HA after I completing config flow, is there anything I missed?

Also, from my point of view, there's no reason to add default config into `configuration.yaml` if we already leverage the power of config flow

2021-05-05 15:02 UTC, tsunglung commented
The notify service was not supported by using config_entry to setup.
It only support setup_platform now.
You still need to config one in configuration.yaml.
For the second, third one, you can use config flow to add.

2021-05-10 09:12 UTC, osk2 commented
@tsunglung Apologize for late reply

I still not able to create second notify service using config flow. Nothing show up in my service list after completing the flow

2021-05-10 09:25 UTC, tsunglung commented
You did not get my point.
Notify sevice did not support config entry setup.
Use config entry to add another client_id.
Then user can to send messages to another client_id by specifying name in the data field.

2021-05-10 09:31 UTC, osk2 commented
Ah that makes sense! I thought config flow is use to create service 🤦🏼  (may confuse users too?)

I'll try again later and see if there's anything we can improve

2021-05-11 13:59 UTC, osk2 requested changes

2021-05-11 13:59 UTC, osk2 commented on custom_components/line_bot/notify.py
> +        for i in self._hass.data[DOMAIN][LINE_BOT]:
This will cause KeyError if user only setup notify service via configuration.yaml

2021-05-12 11:56 UTC, merged